baseURL = "https://nhtithy.github.io"

# https://nhtithy.github.io

languageCode = 'en-us'
title = 'Naznin Hasan'
paginate = 5
buildDrafts =  false
enableEmoji = true
defaultContentLanguage = 'bn'

[languages.bn]
contentDir = "content/bn"
weight = 1
LanguageName = ':bangladesh:'

[languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 2

[taxonomies]
  category = 'categories'
  tag = 'tags'
  series = 'series'

[minify]
disableXML = true
minifyOutput = true

[markup.goldmark.renderer]
unsafe = true

[outputs]
    home = ["HTML", "RSS", "JSON" ]

[permalinks]
posts = '/:year/:month/:day/:filename/'

[module]
  [[module.imports]]
    path = 'github.com/adityatelange/hugo-PaperMod'
