baseURL = ""
# https://nhtithy.github.io

languageCode = 'en-us'
title = 'Naznin Hasan'
paginate = 5
buildDrafts =  false
#contentDir = "content/en"
enableEmoji = true



 

[minify]
disableXML = true
minifyOutput = true

[markup.goldmark.renderer]
unsafe = true

[module]
  [[module.imports]]
    path = 'github.com/adityatelange/hugo-PaperMod'
