[[main]]
identifier = "Post"
name = "Post"
url = "/post/"
weight = 5

[[main]]
identifier = "Categories"
name = "Categories"
url = "/categories/"
weight = 10

[[main]]
identifier = "Tags"
name = "Tags"
url = "/tags/"
weight = 20

[[main]]
identifier = "Archives"
name = "Archives"
url = "/archives/"
weight = 30
