 
[[main]]
identifier = "post"
name = "পোস্ট"
url = "/posts/"
weight = 5

[[main]]
identifier = "categories"
name = "ক্যাটাগরিজ"
url = "/categories/"
weight = 10

[[main]]
identifier = "tags"
name = "ট্যাগস"
url = "/tags/"
weight = 20

[[main]]
identifier = "search"
name = "সার্চ"
url = "/search/"
weight = 20

