env = "production"
defaultTheme = 'dark'
description = "Portfolio site , Place to express my hobbies"
keywords = [ "Blog", "Portfolio", "PaperMod" ]
author =  "Naznin Hasan"
ShowReadingTime =  true
ShowShareButtons =  true
ShowPostNavLinks =  true
ShowBreadCrumbs = true
ShowCodeCopyButtons = false
ShowWordCount = true
ShowRssButtonInSectionTermList = true
UseHugoToc = true
disableSpecial1stPost = false
disableScrollToTop = false
hideSummary =  false
showtoc = true
tocopen = true
comments = true

[label]
text = "@nhtithy"
icon = "/assets/images/avatar.png"
iconHeight = 32


[cover]
image = ['/assets/images/cover.png']
alt = "Cover"
captions = "If you know how, you will know how"


[assets]
favicon = "/assets/icons/favicon/favicon.ico"
favicon16x16 = "/assets/icons/favicon/favicon-16x16.png"
favicon32x32 = "/assets/icons/favicon/favicon-16x16.png"
apple_touch_icon = "/assets/icons/apple/apple-touch-icon.png"
safari_pinned_tab = "/assets/icons/apple/safari-pinned-tab.svg"




[[socialIcons]]
name = "facebook"
url = "https://facebook.com/nazninhasan"

[[socialIcons]]
name = "instagram"
url = "https://instagram.com/nhtithy"

[[socialIcons]]
name = "tiktok"
url = "https://tiktok.com/@naznin_hasan8"

[[socialIcons]]
name = "github"
url = "https://github.com/nhtithy"

[[socialIcons]]
name = "twitter"
url = "https://twitter.com/nhtithy"

[[socialIcons]]
name = "telegram"
url = "https://nazninhasantithy.t.me/"


[fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1_000
threshold = 0.4
minMatchCharLength = 0
keys = [ "title", "permalink", "summary", "content"]
