name: Hugo Deployment
on: push
jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Git Checkout
              uses: actions/checkout@v2

            - name: Setup hugo
              uses: peaceiris/actions-hugo@v2
              with:
                hugo-version: '0.91.2'

            - name: update theme
              run:  hugo mod get -u

            - name: Build Site
              run:  hugo --minify

            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              with:
                personal_token: ${{ secrets.TOKEN }}
                external_repository: nhtithy/nhtithy.github.io
                publish_dir: ./public
                user_name: nhtithy
                user_email: nazninhasan2004@gmail.com
                publish_branch: main
